### ISSUE TITLE
Deploy StageTool

### ISSUE THREAD

**Issue by junelsolis** [Turku-BioImaging/stagetool-ui#6]
## Milestones
- [x] Build UI
- [x] Configure staging environment on CSC services
- [x] Deploy to staging environment

## To do items
- [x] Implement additional pages
- [x] Make UI work on wider viewports [ End of May 2024 ]
- [x] Read updated API data structure
- [x] Allow image uploads from home page
- [x] Show predictions in output page
